# Form implementation generated from reading ui file 'interfaceTest.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


import grid_world
import q_learning_agent
from q_learning_agent import QLearningAgent
import numpy as np
import random


class Ui_Form(object):


    def action1(self):
        l = list()
        if self.radioButton_12.isChecked() :
            for i in range(int(self.spinBox_13.value())) :
                aux = [random.randint(0 , int(self.horizontalSlider_5.value())) , random.randint(0 , int(self.horizontalSlider_5.value()))]
                while aux in l :
                    aux = [random.randint(0 , int(self.horizontalSlider_5.value())) , random.randint(0 , int(self.horizontalSlider_5.value()))]
                l.append(aux)
        env = grid_world.GridWorldEnv(int(self.horizontalSlider_5.value()), l)
        q_learning_agent = QLearningAgent(env)

        # training variables
        num_episodes = int(self.spinBox_14.value())
        max_steps = int(self.spinBox_15.value())

        # We reset the environment for the first time
        observation, info = env.reset(first_reset=True, return_info=True)
        state = env.state_table.index(list(observation['agent']))

        # training
        q_learning_agent.learn(num_episodes, max_steps, env, state)



        # watch trained agent
        for i in range(5) :
            observation = env.reset()
            state = env.state_table.index(list(observation['agent']))
            done = False
            rewards = 0

            for s in range(max_steps):

                action = np.argmax(q_learning_agent.qtable[state, :])
                observation, reward, done, info = env.step(action)
                new_state = env.state_table.index(list(observation['agent']))
                rewards += reward
                env.render(q_learning_agent.qtable)
                state = new_state

                if done:
                    break
        env.close()

    def action2(self):
        from simple_grid_world import GridWorldEnvMC
        from q_learning_agent_mc import QLearningAgentMC
        from agent_monte_carlo import Agent_MC
        from maze_world_mc import MazeWorldMC
        import numpy as np


        if self.radioButton_9.isChecked():
            env2 = MazeWorldMC(int(self.horizontalSlider_4.value()), int(self.spinBox_10.value()))
        elif self.radioButton_8.isChecked():
            env2 = MazeWorldMC(int(self.horizontalSlider_4.value()), 0)
        agent = QLearningAgentMC(env2)
        num_episodes = int(self.spinBox_11.value())
        max_steps = int(self.spinBox_12.value())

        #training
        agent.learn(num_episodes, max_steps, env2)


        env2.save_map(agent.qtable)

        #watch trained agent
        for i in range(10):
            # watch trained agent
            observation = env2.reset()
            state = env2.state_table.index(list(observation['agent']))
            done = False
            rewards = 0

            for s in range(max_steps):

                action = np.argmax(agent.qtable[state, :])
                observation, reward, done, info = env2.step(action)
                new_state = env2.state_table.index(list(observation['agent']))
                rewards += reward
                env2.render(agent.qtable)
                if (np.array_equal(state, new_state)):
                    break
                state = new_state

                if done :
                    break
        env2.close()




    def action3(self):
        import gym
        from q_learning_agent_s import QLearningAgentS
        import numpy as np
        from maze_world_s import MazeWorldS
        import random

        # Press the green button in the gutter to run the script.

        # env = gym.make('gym_examples/GridWorld-v0')
        env = MazeWorldS(int(self.horizontalSlider_3.value()), int(self.spinBox_9.value()))
        env.action_space.seed(42)

        # initialisation de l'agent
        q_learning_agent = QLearningAgentS(env)

        # training variables
        num_episodes = int(self.spinBox_8.value())
        max_steps = int(self.spinBox_7.value())

        # We reset the environment for the first time
        observation, info = env.reset(first_reset=True, return_info=True)
        state = env.state_table.index(list(observation['agent']))

        # training
        q_learning_agent.learn(num_episodes, max_steps, env, state)
        #q_learning_agent.learn(num_episodes, max_steps, env)


        # watch trained agent
        for i in range(5):
            observation = env.reset()[0]
            state = env.state_table.index(list(observation['agent']))
            done = False
            rewards = 0

            for s in range(max_steps):

                action = np.argmax(q_learning_agent.qtable[state, :])
                observation, reward, done, info = env.step(action)
                new_state = env.state_table.index(list(observation['agent']))
                rewards += reward
                env.render(q_learning_agent.qtable)
                state = new_state

                if done :
                    break
        env.close()

    def changeMaxSpinBox1(self):
        self.spinBox_13.setMaximum(int(0.4 * (int)(self.horizontalSlider_5.value())**2))
        self.label_31.setText(str(int(self.horizontalSlider_5.value())))


    def changeMaxSpinBox2(self):
        self.spinBox_10.setMaximum(int(0.4 * (int)(self.horizontalSlider_4.value())**2))
        self.label_25.setText(str(int(self.horizontalSlider_4.value())))


    def changeMaxSpinBox3(self):
        self.spinBox_9.setMaximum(int(0.4 * (int)(self.horizontalSlider_3.value())**2))
        self.label_15.setText(str(int(self.horizontalSlider_3.value())))

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(646, 441)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.QLearning = QtWidgets.QWidget()
        self.QLearning.setObjectName("QLearning")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.QLearning)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.QLearning)
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 574, 371))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 9, 2, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_5)
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setAutoRepeat(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_5.addWidget(self.radioButton_11, 4, 1, 1, 2)
        self.radioButton_12 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_5)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_5.addWidget(self.radioButton_12, 5, 1, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 6, 2, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_5)
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_13.setMaximum(1000)
        self.spinBox_13.setMinimum(10)
        self.gridLayout_5.addWidget(self.spinBox_13, 6, 3, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_5)
        self.spinBox_14.setMinimum(50)
        self.spinBox_14.setMaximum(10000)
        self.spinBox_14.setSingleStep(10)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_5.addWidget(self.spinBox_14, 1, 1, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 3, 0, 1, 2)
        self.spinBox_15 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_5)
        self.spinBox_15.setMinimum(10)
        self.spinBox_15.setMaximum(10000)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_5.addWidget(self.spinBox_15, 2, 1, 1, 2)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 0, 1, 1)
        #self.textEdit_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        #self.textEdit_3.setObjectName("textEdit_3")
        #self.gridLayout_5.addWidget(self.textEdit_3, 8, 2, 1, 1)
        """
        self.radioButton_13 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_5)
        self.radioButton_13.setObjectName("radioButton_13")
        """
        #self.gridLayout_5.addWidget(self.radioButton_13, 7, 1, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 0, 3, 1, 1)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.scrollAreaWidgetContents_5)
        self.horizontalSlider_5.setMinimum(5)
        self.horizontalSlider_5.setMaximum(25)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout_5.addWidget(self.horizontalSlider_5, 0, 1, 1, 2)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_6.addWidget(self.scrollArea_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.QLearning, "")
        self.MonteCarlo = QtWidgets.QWidget()
        self.MonteCarlo.setObjectName("MonteCarlo")
        self.gridLayout = QtWidgets.QGridLayout(self.MonteCarlo)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.MonteCarlo)
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 574, 371))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 9, 2, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setAutoRepeat(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_4.addWidget(self.radioButton_8, 4, 1, 1, 2)
        self.radioButton_9 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_4.addWidget(self.radioButton_9, 5, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 6, 2, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_4.addWidget(self.spinBox_10, 6, 3, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        self.spinBox_11.setMinimum(50)
        self.spinBox_11.setMaximum(10000)
        self.spinBox_11.setSingleStep(10)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout_4.addWidget(self.spinBox_11, 1, 1, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 0, 1, 2)
        self.spinBox_12 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        self.spinBox_12.setMinimum(10)
        self.spinBox_12.setMaximum(10000)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_4.addWidget(self.spinBox_12, 2, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 2, 0, 1, 1)
        #self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_4)
        #self.textEdit_2.setObjectName("textEdit_2")
        #self.gridLayout_4.addWidget(self.textEdit_2, 8, 2, 1, 1)
        """
        self.radioButton_10 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.radioButton_10.setObjectName("radioButton_10")
        """
        #self.gridLayout_4.addWidget(self.radioButton_10, 7, 1, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 3, 1, 1)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.scrollAreaWidgetContents_4)
        self.horizontalSlider_4.setMinimum(5)
        self.horizontalSlider_4.setMaximum(25)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout_4.addWidget(self.horizontalSlider_4, 0, 1, 1, 2)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.MonteCarlo, "")
        self.SARSA = QtWidgets.QWidget()
        self.SARSA.setObjectName("SARSA")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SARSA)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.SARSA)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 574, 371))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 9, 2, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setAutoRepeat(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_3.addWidget(self.radioButton_6, 4, 1, 1, 2)
        self.radioButton_5 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_3.addWidget(self.radioButton_5, 5, 1, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 2, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_3.addWidget(self.spinBox_9, 6, 3, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_8.setMinimum(50)
        self.spinBox_8.setMaximum(10000)
        self.spinBox_8.setSingleStep(10)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_3.addWidget(self.spinBox_8, 1, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 2)
        self.spinBox_7 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_7.setMinimum(10)
        self.spinBox_7.setMaximum(10000)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_3.addWidget(self.spinBox_7, 2, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        #self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        #self.textEdit.setObjectName("textEdit")
        #self.gridLayout_3.addWidget(self.textEdit, 8, 2, 1, 1)
        """
        self.radioButton_7 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_7.setObjectName("radioButton_7")
        """
        #self.gridLayout_3.addWidget(self.radioButton_7, 7, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 3, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.horizontalSlider_3.setMinimum(5)
        self.horizontalSlider_3.setMaximum(25)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout_3.addWidget(self.horizontalSlider_3, 0, 1, 1, 2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.SARSA, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalSlider_5.actionTriggered.connect(self.changeMaxSpinBox1)
        self.horizontalSlider_4.actionTriggered.connect(self.changeMaxSpinBox2)
        self.horizontalSlider_3.actionTriggered.connect(self.changeMaxSpinBox3)
        self.pushButton_5.clicked.connect(self.action1)
        self.pushButton_4.clicked.connect(self.action2)
        self.pushButton_3.clicked.connect(self.action3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "RL Maze Pathfinder"))
        self.label.setText(_translate("Form", "Welcome to our RL Maze solver !!"))
        self.pushButton_5.setText(_translate("Form", "Generate"))
        self.radioButton_11.setText(_translate("Form", "NO"))
        self.radioButton_12.setText(_translate("Form", "YES, RANDOMLY"))
        self.label_26.setText(_translate("Form", "If \"YES\", how many "))
        self.label_27.setText(_translate("Form", "Episodes"))
        self.label_28.setText(_translate("Form", "Maze size"))
        self.label_29.setText(_translate("Form", "Generate Walls"))
        self.label_30.setText(_translate("Form", "Max_iter"))
        #self.radioButton_13.setText(_translate("Form", "YES BY INPUT"))
        self.label_31.setText(_translate("Form", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.QLearning), _translate("Form", "QLearinig"))
        self.pushButton_4.setText(_translate("Form", "Generate"))
        self.radioButton_8.setText(_translate("Form", "NO"))
        self.radioButton_9.setText(_translate("Form", "YES, RANDOMLY"))
        self.label_20.setText(_translate("Form", "If \"YES\", how many "))
        self.label_21.setText(_translate("Form", "Episodes"))
        self.label_22.setText(_translate("Form", "Maze size"))
        self.label_23.setText(_translate("Form", "Generate Walls"))
        self.label_24.setText(_translate("Form", "Max_iter"))
        #self.radioButton_10.setText(_translate("Form", "YES BY INPUT"))
        self.label_25.setText(_translate("Form", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MonteCarlo), _translate("Form", "MonteCarlo"))
        self.pushButton_3.setText(_translate("Form", "Generate"))
        self.radioButton_6.setText(_translate("Form", "NO"))
        self.radioButton_5.setText(_translate("Form", "YES, RANDOMLY"))
        self.label_17.setText(_translate("Form", "If \"YES\", how many "))
        self.label_14.setText(_translate("Form", "Episodes"))
        self.label_18.setText(_translate("Form", "Maze size"))
        self.label_19.setText(_translate("Form", "Generate Walls"))
        self.label_16.setText(_translate("Form", "Max_iter"))
        #self.radioButton_7.setText(_translate("Form", "YES BY INPUT"))
        self.label_15.setText(_translate("Form", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SARSA), _translate("Form", "SARSA"))



"""
if __name__ =="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
"""